### ISSUE TITLE
设置自定义的https接口后出错

### ISSUE THREAD

**Issue by Chalkim** [Cangqifeng/AnimeSearcherUI#2]
修改数据接口链接为`https://$HOST/anime-api/`后，前端无法进行wss连接，搜索过程无法停止且不显示结果。（`http://localhost:6001/`反向代理到`https://$HOST/anime-api/`）

wss接口保证可用
![wss](https://user-images.githubusercontent.com/37498010/126044809-575db2dc-1003-4cb1-8866-5defbdb2c5a9.png)

**Comment by nymanyim** [comment]
？？？
可以用https协议了吗，我记得之前改完前端与部分后端，搜索啥正常了，但是视频加载不了呀

**Comment by Chalkim** [comment]
我是用nginx做的反向代理，自己有申请域名和SSL证书，经过反向代理之后流量都会走个TLS协议。这里前端应该主要是通过WebSocket协议来查询结果的。

https://github.com/lozyue/AnimeSearcherUI/blob/7d8dbb26a398f5ecaa866c72f3c007ac1e6aa9d4/src/Pages/HelloWorld.vue#L345

问题在于ws默认走80端口，而经过tls协议的wss默认走443端口。表现出来的现象是搜索过程不呈现结果且无法停止，原因大概是前端试图从80端口找ws，但是被防火墙阻止了。（如果没有设置防火墙并且写了反代的话应该通过 HTTP Upgrade 还是可以查询的吧，但是既然使用了https就应该全站都过TLS）我有在 https://github.com/lozyue/AnimeSearcherUI/pull/3 改了处理方法，测试了用https是没有问题的。（http没有测试）

关于使用https协议视频无法加载的问题，原因应该是后端对URL的处理问题，参考 https://github.com/zaxtyson/AnimeSearcher/issues/22 。

**Comment by lozyue** [comment]
[AnimeUI-v2-alpha-pre](https://github.com/lozyue/AnimeSearcherUI/tree/webui) 预览版已经放出来了，WebUI对于自由修改通信地址的支持已经基本完善。
https的问题目前主要再与 anime-api server端没有提供直接支持，但反代的方式理论上能正常使用了。
目前请使用这个分支作为搭配新版UI的server端:  [AnimeSearcher/tree/add-storage](https://github.com/zaxtyson/AnimeSearcher/tree/add-storage)
