### ISSUE TITLE
新番表数据过多，造成css溢出

### ISSUE THREAD

**Issue by nymanyim** [Cangqifeng/AnimeSearcherUI#4]
最近后端版本更新了，放服务器发现某些引擎的新番表数据获取过多，底部超出了很大一截：
![image](https://user-images.githubusercontent.com/54471703/127744479-8aed00fe-843f-4dff-8c77-3731b43becec.png)
希望大大在下版本可以更新一下这部分，建议：将新番表class由col3改为col3-2并设置以下值为最佳
.col-3-2{flex:0 0 25%;max-width:25%;height: 2250px;overflow: scroll;}
那个滚动条的背景颜色是真的晃眼—_—!!，可以考虑在col3-2时隐藏

**Comment by nymanyim** [comment]
后端agefans引擎有个问题会造成前端详情播放页面封面图不显示，封面链接被定义为域名+封面url：
![image](https://user-images.githubusercontent.com/54471703/127746631-011ba89c-925b-4c2c-9ad3-8be701d83ff5.png)
解决方式：去掉图示部分即可。
![image](https://user-images.githubusercontent.com/54471703/127746584-5ce92f80-a1ea-4c35-bbd9-e79347c880f5.png)

**Comment by lozyue** [comment]
[AnimeUI-v2-alpha-pre](https://github.com/lozyue/AnimeSearcherUI/tree/webui) 预览版已经放出来了
对于新番表已经单独占用一个页面作为展示，同时增加了对移动端的支持。（不过PWA现在还不是很稳定）
滚动条部分预览版目前没有添加，之后会考虑添加到主题中并提供自定义选项。

---

后端引擎因为经常变动比较大， @zaxtyson 的维护压力很大，细节问题可能比较多，单靠issue改动效率可能太低了，细节问题可以先自行修改，看之后对这块单独开个汇总？这部分zaxtyson已经在想办法了，还请期待后续。

**Comment by lozyue** [comment]
v2-alpha0已经更新了，关于滚动条颜色的定制暂时先交由主题控制了，来不及添加选项了。
封面链接的这个问题确实现在都还存在……
